# HTB Discord Bot Service Configuration
# All settings for the unified HTB Discord integration service

# Core API Configuration
api:
  discord_token: "${DISCORD_TOKEN}"
  htb_bearer_token: "${HTB_BEARER_TOKEN}"
  linkwarden_api_url: "${LINKWARDEN_API_URL:-}"
  linkwarden_token: "${LINKWARDEN_TOKEN:-}"

# Discord Channel Configuration
channels:
  # General announcement channel for challenges
  general_channel_id: "${GENERAL_CHANNEL_ID}"

  # Machine-specific channels
  machines_channel_id: "${MACHINES_CHANNEL_ID}"
  machines_voice_channel_id: "${MACHINES_VOICE_CHANNEL_ID}"
  machines_forum_channel_id: "${FORUM_CHANNEL_ID}"

  # Challenge-specific channels
  challenges_voice_channel_id: "${CHALL_VOICE_CHANNEL_ID}"
  challenges_forum_channel_id: "${CHALL_FORUM_CHANNEL_ID}"

  # Error/notice channel
  error_channel_id: "${ERROR_CHANNEL_ID}"

# Feature Configuration - Enable/Disable specific features
features:
  machines:
    enabled: true
    create_events: true
    create_forum_threads: true
    send_announcements: true
    poll_interval: 600  # seconds

  challenges:
    enabled: true
    create_events: true
    create_forum_threads: true
    send_announcements: true
    poll_interval: 600  # seconds

  notices:
    enabled: true
    poll_interval: 60  # seconds

  osint:
    enabled: true
    command_prefix: "!"

  linkwarden:
    enabled: false  # Disabled by default
    categories_to_monitor: []  # List of Discord category IDs
    rate_limit:
      links_per_batch: 10
      batch_interval: 6  # seconds

  ics_feed:
    enabled: true
    secret_path: ""   # z.B. "9b2f6c02-2b7a-4f0e-8c2f-6a1f9b63a3a4"; leer = direkt /calendar.ics
    lookback_days: 30
    lookahead_days: 120
    default_duration_minutes: 120   # wenn kein dtend vorhanden
    prodid: "-//HTB-Discord//ICS Feed//EN"    

# Database Configuration
database:
  # SQLite database files
  machines_db: "data/machines.db"
  challenges_db: "data/challenges.db"
  notices_db: "data/notices.db"
  links_db: "data/links.db"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/htb_discord.log"
  max_file_size: "10MB"
  backup_count: 5

# Service Configuration
service:
  name: "htb-discord-service"
  description: "HackTheBox Discord Integration Service"
  restart_on_failure: true
  max_restarts: 5
  restart_delay: 30  # seconds

# Discord Bot Configuration
discord:
  intents:
    message_content: true
    guilds: true
    messages: true
  activity:
    type: "playing"  # playing, streaming, listening, watching
    name: "HackTheBox"
